name: Angular CRUD CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd angular-crud
        npm ci
        npm run build --if-present
        npm test
        npm run coverage
        npm link
        cd ../demo
        npm install
        npm link angular-crud
        mkdir -p src/app/hotel
        cp model.json src/app/hotel/.
        ng g angular-crud:crud-module hotel
        npm test
      env:
        CI: true
